baseURL = 'https://dora.dev/'
languageCode = 'en-us'
theme = 'dora'

[markup.goldmark.renderer]
unsafe= true

[params]
    Keywords = "DevOps, Lead time, Deploy frequency, Change fail rate, MTTR, Time to restore, metrics, DORA"
    Description = "DevOps Research and Assessment (DORA) is a long running research program that seeks to understand the capabilities that drive software delivery and operations performance. DORA helps teams apply those capabilities, leading to better organizational performance."

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[[cascade]]
  [cascade._target]
    path = "**/README.md"
  [cascade._build]
    render = "never"
    list = "never"