steps:

  # - name: gcr.io/$PROJECT_ID/hugo
  #   script: |
  #     # Build the draft version of the site (this will include content where the front matter specifies Draft: true)
  #     hugo -D -v -s ./hugo -d /workspace/hugo/draft --debug

  #     # Build the prod version of the site (this will omit content where the front matter specifies Draft: true)
  #     hugo -v -s ./hugo -d /workspace/hugo/public --debug

  # - name: gcr.io/cloud-builders/npm:node-16.18.0
  #   entrypoint: npm
  #   dir: 'functions/inquiry-monitor'
  #   args: ['install']

  # - name: gcr.io/$PROJECT_ID/firebase
  #   script: |
  #     firebase deploy --only hosting --project=$PROJECT_ID

  - name: 'bash'
    env: 
    - 'COMMIT=$COMMIT_SHA'
    script: |
      # install github cli
      apk update && apk add github-cli

      gh version

      # authenticate
      set +x
      echo "$GH_TOKEN" > .githubtoken
      set -x
      unset GH_TOKEN
      gh auth login --with-token < .githubtoken

      # add preview URL as comment
      gh api \
      --method POST \
      -H "Accept: application/vnd.github+json" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      /repos/dora-team/dora.dev/deployments \
      -f ref='main' \
      -f payload='{ "deploy": "(commit)" }' \
      -f description='Deployment initiated by Cloud Build' 
    secretEnv: ['GH_TOKEN']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
    env: 'GH_TOKEN'