steps:
  - name: gcr.io/$PROJECT_ID/hugo
    id: 'hugo'
    args: [
      "-v", "-s", "./hugo",
      "-d", "/workspace/hugo/public",
      "--debug"
      ]

  - name: gcr.io/$PROJECT_ID/firebase
    script: |
      firebase deploy --only hosting --project=$PROJECT_ID