steps:
  - name: 'bash'
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    script: |
      # Copy correct Firestore config per project
      cp hugo/static/js/firebase-config.${PROJECT_ID}.js /workspace/hugo/static/js/firebase-config.js

  - name: 'ubuntu'
    script: |
      #! /usr/bin/env bash

      apt update && apt install wget -y

      # install hugo "extended"
      HUGO_VERSION=0.114.1
      wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb -O /tmp/hugo.deb

      apt install /tmp/hugo.deb

      # Build the prod version of the site (this will omit content where the front matter specifies Draft: true)
      hugo -v -s ./hugo -d /workspace/hugo/public --logLevel=debug

  - name: gcr.io/cloud-builders/npm:node-16.18.0
    entrypoint: npm
    dir: 'functions/inquiry-monitor'
    args: ['install']

  - name: 'ubuntu'
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    script: |
      apt update && apt install curl sudo -y
      curl -sL https://firebase.tools | bash

      # BUG: there is a bug in Firebase that is causing issues when installing the extension on staging
      # see: https://github.com/firebase/firebase-tools/issues/6060
      # so we'll skip the extension until that's fixed

      firebase deploy --non-interactive --project=${PROJECT_ID} --except=extensions
