steps:

  - name: 'ubuntu'
    script: |
      #! /usr/bin/env bash

      apt update && apt install wget -y

      # install hugo "extended"
      HUGO_VERSION=0.114.1
      wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb -O /tmp/hugo.deb

      apt install /tmp/hugo.deb

      # Build the prod version of the site (this will omit content where the front matter specifies Draft: true)
      hugo -v -s ./hugo -d /workspace/hugo/public --logLevel=debug

  - name: gcr.io/cloud-builders/npm:node-16.18.0
    entrypoint: npm
    dir: 'functions/inquiry-monitor'
    args: ['install']

  - name: gcr.io/$PROJECT_ID/firebase
    script: |
      firebase deploy --project=doradotdev-staging
