steps:
  - name: gcr.io/$PROJECT_ID/hugo
    id: 'hugo'
    args: [
      "-v","-s","./hugo",
      "-d","/workspace/hugo/public",
      "--debug"
      ]
  
  # TODO: use a pre-built Firebase builder instead of installing the CLI on the fly
  - name: gcr.io/$PROJECT_ID/firebase
    args: [
      "hosting:channel:deploy", "pr-test-1", 
      "--project=$PROJECT_ID"
    ]

  # # add preview URL as a status check
  # # prereq: a github token exists in Secret manager, named with the name specified by `github-token-secret-name`
  # # the token must have access: `repo:status` (or `repo:all` for a private repo)
  # - name: 'gcr.io/${PROJECT_ID}/pr-status-poster'
  #   id: 'status'
  #   args: [
  #     '--project-id', '${PROJECT_ID}', 
  #     '--repo-name', 'dora-team/${REPO_NAME}',
  #     '--commit-sha', '${COMMIT_SHA}',
  #     '--target-url', 'https://commit$SHORT_SHA---preview-doradotdev-gr5oklvxhq-uc.a.run.app',
  #     '--github-token-secret-name', 'github_token'
  #   ]
  #   waitFor: ['deploy']