steps:
  - id: 'Stage FirebaseConfig'
    name: 'bash'
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    script: |
      # Copy correct Firestore config per project
      cp -v ci/firebase-config.${PROJECT_ID}.js /workspace/hugo/static/js/firebase-config.js

  - id: 'Hugo Build Staging Site'
    name: 'ubuntu'
    script: |
      #! /usr/bin/env bash

      apt update && apt install wget -y

      # install hugo "extended"
      HUGO_VERSION=0.114.1
      wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb -O /tmp/hugo.deb

      apt install /tmp/hugo.deb

      # Build the prod version of the site (this will omit content where the front matter specifies Draft: true)
      hugo -v -s ./hugo -d /workspace/hugo/public --logLevel=debug

  - id: 'Node Install'
    name: gcr.io/cloud-builders/npm:node-16.18.0
    entrypoint: npm
    dir: 'functions/inquiry-monitor'
    args: ['install']

  - id: 'Unit Testing'
    name: 'openjdk:20-ea-jdk-slim'
    dir: 'functions/inquiry-monitor'
    env:
      - 'MONITOR_SEND_TO=no-reply@example.com'
    script: |
      apt update && apt install curl sudo -y
      curl -sL https://firebase.tools | bash

      apt install nodejs sudo -y
      apt install npm sudo -y
      firebase emulators:exec 'npm run emulator-test' --only firestore,functions

  - id: 'Firebase (re)Deploy All'
    name: 'ubuntu'
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    script: |
      apt update && apt install curl sudo -y
      curl -sL https://firebase.tools | bash

      # skip remote config
      firebase deploy --non-interactive --force --project=${PROJECT_ID} --except=remoteconfig
